#!/bin/bash

##train marco data
##!!!! make sure set --chdir to your current working directory

#SBATCH --job-name=marco

#SBATCH --account=stf
#SBATCH --partition=ckpt

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=40
#SBATCH --time=3:30:00

#SBATCH --mem=170G
#SBATCH --chdir=/gscratch/scrubbed/[Youruwnetid]/

#SBATCH --export=all
module load foster/python/miniconda/3.8
eval "$(conda shell.bash hook)"
conda activate marco3
export OMP_NUM_THREADS=4
python3 marco.py > output
